### PR TITLE
Various fixes

### LINKED ISSUE #479: Mobile: zoom in/out from user's location takes you back to last location
This issue is happening on mobile (I'm using an iPhoneX, Chrome). 

Steps to reproduce:
1) On map view, select any location on the map (e.g. some city in Missouri), see location panel open. Close location panel to reveal the map again.
2) Using zoom controls, use the last/bottom zoom button to automatically zoom into the user's location (e.g. mine zooms in to La Jolla, San Diego)
3) Then manually zoom in or out on the map, see the map goes back to previous location (Missouri) instead of zooming in/out of San Diego

### LINKED ISSUE #480: Location Comparison: disable "load similar" for states
Feedback from client: We do not plan on having similar places for states since there are so few of them. Yes, please disable.

To do: disable the "load similar places" button on the Location Comparison dialog when a state is selected. And add a tooltip explaining why (I will get copy from client)

### LINKED ISSUE #498: Compare locations CSV: remove all Native American estimates
Remove all estimates related to Native Americans in the Compare Locations export since we are not going live with Native American estimates in this release

Steps to reproduce:
1) Select 2+ places on the map
2) In location panel, click COMPARE LOCATIONS
3) in location comparison dialog, click EXPORT CSV 
4) in export, see there are still columns with Native American data. example here - all columns in red should be removed: https://docs.google.com/spreadsheets/d/1du-pA9ANQsHFiLy4HF0ofMWGOlxztk0QsHaqZrFwdiY/edit#gid=1772039747

Expected result: the CSV export does not include any native american estimates or data

### LINKED ISSUE #499: Location comparison: "load similar" blank screen
For some locations, when clicking LOAD SIMILAR in the location comparison dialog, a blank screen appears instead of loading more locations.

Video here: https://www.loom.com/share/557d07c1255141908c2200fb670e67d4

Steps to reproduce:
1) find a location e.g. Humboldt County School District or Harvard MA school district
2) in location panel, click COMPARE LOCATIONS button
3) in location comparison dialog, click LOAD SIMILAR
4) see a blank screen appears 

Expected results: similar locations load in the dialog

### PR DESCRIPTION
**Pull request by touchRED**
Closes #498, closes #480, fixes #499, fixes #479.

Viewable [here](https://focused-engelbart-a57f5e.netlify.app/).

Notes:
- Since we were forced to ditch the Mapbox geolocator and reimplement it using `flyToViewport`, activating geolocation **no longer displays a blue dot at the user's location**.
- Loading similar locations is now disabled for states, showing an explanatory tooltip on hover.

### CODE REVIEW

File: src/modules/explorer/compare/components/CompareDialog.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ function CompareDialog({ classes, ...props }) {
         <div className={classes.toolbar}>
           <CompareDemographicSelect />
           <CompareSearch />
-          <CompareLoadSimilarButton />
+          <CompareLoadSimilarButton hideForStates={region === 'states'} />
```
Comment (Lane) [inline src/modules/explorer/compare/components/CompareDialog.js:100]: no need for the `hideForStates` prop, the `CompareLoadSimilarButton` has the currently selected location data, which you can use to get the region

File: src/modules/explorer/compare/components/CompareLoadSimilarButton.js [hunk 2]
```diff
@@ -20,13 +20,15 @@ const fetchSimilarLocations = locationId => {
...
         .split(',')
-        .filter(id => id !== locationId)
+        .filter(id => id !== locationId && !!getRegionFromLocationId(id))
       return otherIds
     }
   )
 }
 
-const CompareLoadSimilarButton = ({ ...props }) => {
+const CompareLoadSimilarButton = ({ hideForStates, ...props }) => {
```
Comment (Lane) [inline src/modules/explorer/compare/components/CompareLoadSimilarButton.js:29]: remove `hideForStates` prop.  within the component use 

`const isStateLevel = getRegionForLocationId(selectedLocation)`

File: src/modules/explorer/compare/components/CompareLoadSimilarButton.js [hunk 3]
```diff
@@ -46,28 +48,33 @@ const CompareLoadSimilarButton = ({ ...props }) => {
...
       addCompareLocations(ids)
       setState({ loading: false, loaded: true })
     })
-  }
+  }, [setState, addCompareLocations, locationData])
 
   return locationData ? (
     <Tooltip
-      title={getLang('LOAD_SIMILAR_HINT', {
+      title={hideForStates ? 'Loading similar regions is optimized for districts, counties, and schools.' : getLang('LOAD_SIMILAR_HINT', {
```
Comment (Lane) [inline src/modules/explorer/compare/components/CompareLoadSimilarButton.js:63]: use the `isStateLevel` (from above) to determine which tooltip text.  also, do not hardcode this text, instead put the string in the [explorer language](https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0) sheet with an associated key (e.g `LOAD_SIMILAR_STATES_HINT`)

File: src/modules/explorer/compare/components/CompareLoadSimilarButton.js [hunk 4]
```diff
@@ -46,28 +48,33 @@ const CompareLoadSimilarButton = ({ ...props }) => {
...
-        onClick={handleLoadSimilar}
-        {...props}>
-        {state.loading
-          ? getLang('LABEL_LOADING')
-          : getLang('LOAD_SIMILAR_BUTTON')}
-      </Button>
+      <span>
+        <Button
+          variant="outlined"
+          disabled={state.loaded || hideForStates}
```
Comment (Lane) [inline src/modules/explorer/compare/components/CompareLoadSimilarButton.js:69]: use `isStateLevel` instead of `hideForStates` prop

**Review by Lane — CHANGES_REQUESTED** [review]
geolocation looking good!

a few small touchups on the tooltip for `<CompareLoadSimilarButton />`:
- use the currently selected location to determine `region` from within the component, instead of passing a prop
- make sure any language in the explorer is not hardcoded and comes from the [explorer language google sheet](https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0).

File: src/modules/explorer/compare/components/CompareLoadSimilarButton.js [hunk 5]
```diff
@@ -58,15 +56,17 @@ const CompareLoadSimilarButton = ({ hideForStates, ...props }) => {
     })
   }, [setState, addCompareLocations, locationData])
 
+  const isStateLevel = useMemo(() => locationData && getRegionFromLocationId(locationData.id) === 'states', [locationData])
```
Comment (Lane) [inline src/modules/explorer/compare/components/CompareLoadSimilarButton.js:59]: this works, but we [don't need to use useMemo](https://kentcdodds.com/blog/usememo-and-usecallback#whats-the-point) here because:
- the computation of the `isStateLevel` boolean is not an expensive operation
- the resulting value of `isStateLevel` is a boolean, it has [referential equality](https://kentcdodds.com/blog/usememo-and-usecallback#referential-equality) to other boolean values (unlike objects / arrays)

**Review by Lane — CHANGES_REQUESTED** [review]
looks good, one more small change in regards to `useMemo`

**Comment by touchRED** [comment]
@Lane: How's this?

`const isStateLevel = locationData && getRegionFromLocationId(locationData.id) === 'states'`

**Comment by Lane** [comment]
@touchRED great, thanks!
